// Copyright Epic Games, Inc. All Rights Reserved.

#include "Core/EclipseGameplayTags.h"

namespace EclipseTags
{
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Attacking, "State.Attacking", "Character is in an attack ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Dodging, "State.Dodging", "Character is in a dodge ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Blocking, "State.Blocking", "Character is holding block")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Parrying, "State.Parrying", "Character is in a parry ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Staggered, "State.Staggered", "Poise broken, character is staggered")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_HitReact, "State.HitReact", "Character is playing a hit reaction")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Dead, "State.Dead", "Character is dead")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Invulnerable, "State.Invulnerable", "Damage is ignored (dodge i-frames)")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Sprinting, "State.Sprinting", "Character is sprinting")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Resting, "State.Resting", "Character is resting at a rest point")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Window_Combo, "Window.Combo", "Montage window where the next combo attack may chain")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Window_Cancel, "Window.Cancel", "Montage window where an attack may be cancelled (dodge)")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Window_Parry, "Window.Parry", "Montage window where a parry succeeds")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Window_Invulnerable, "Window.Invulnerable", "Montage window granting invulnerability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Attack_Light, "Ability.Attack.Light", "Light attack ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Attack_Heavy, "Ability.Attack.Heavy", "Heavy attack ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Attack_Sprint, "Ability.Attack.Sprint", "Sprint attack ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Attack_Riposte, "Ability.Attack.Riposte", "Riposte attack ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Dodge, "Ability.Dodge", "Dodge ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Block, "Ability.Block", "Block ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Parry, "Ability.Parry", "Parry ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Sprint, "Ability.Sprint", "Sprint ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_UseItem, "Ability.UseItem", "Use item ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_HitReact, "Ability.HitReact", "Hit reaction ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Death, "Ability.Death", "Death ability")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_HitReact_Light, "Event.HitReact.Light", "Gameplay event: light hit reaction")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_HitReact_Heavy, "Event.HitReact.Heavy", "Gameplay event: heavy hit reaction")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_HitReact_Stagger, "Event.HitReact.Stagger", "Gameplay event: poise broken")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Death, "Event.Death", "Gameplay event: health reached zero")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Parried, "Event.Parried", "Gameplay event: attacker was parried")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Boss_Defeated, "Event.Boss.Defeated", "Event bus channel: a boss was defeated")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Player_Died, "Event.Player.Died", "Event bus channel: the player died")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Player_Rested, "Event.Player.Rested", "Event bus channel: the player rested")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_World_ShortcutOpened, "Event.World.ShortcutOpened", "Event bus channel: a shortcut was opened")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Item_Acquired, "Event.Item.Acquired", "Event bus channel: an item was acquired")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Data_Damage_Physical, "Data.Damage.Physical", "SetByCaller: physical damage")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Data_Damage_Fire, "Data.Damage.Fire", "SetByCaller: fire damage")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Data_Damage_Magic, "Data.Damage.Magic", "SetByCaller: magic damage")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Data_Damage_Poise, "Data.Damage.Poise", "SetByCaller: poise damage")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Data_Cost_Stamina, "Data.Cost.Stamina", "SetByCaller: stamina cost")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Weapon_Type_StraightSword, "Weapon.Type.StraightSword", "Weapon type: straight sword")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Weapon_Type_GreatSword, "Weapon.Type.GreatSword", "Weapon type: great sword")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Weapon_Type_Spear, "Weapon.Type.Spear", "Weapon type: spear")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Weapon_Type_Shield, "Weapon.Type.Shield", "Weapon type: shield")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(GameplayCue_Hit_Flesh, "GameplayCue.Hit.Flesh", "Cue: hit on flesh")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(GameplayCue_Hit_Armor, "GameplayCue.Hit.Armor", "Cue: hit on armor")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(GameplayCue_Block, "GameplayCue.Block", "Cue: blocked hit")
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(GameplayCue_Parry, "GameplayCue.Parry", "Cue: parry")
}
